# Generated by Django 2.2.2 on 2019-11-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('hostname', models.TextField()),
                ('remote_address', models.TextField()),
                ('method', models.TextField()),
                ('request_data', models.TextField(null=True)),
                ('status_code', models.IntegerField(default=500)),
                ('response', models.TextField(null=True)),
                ('response_time', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
