# Generated by Django 2.2.2 on 2019-10-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default='// Code here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='input',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
