# Generated by Django 2.2.2 on 2019-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20191023_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='languages',
            field=models.CharField(choices=[('c', 'c'), ('c++', 'c++')], default='c', max_length=9),
        ),
    ]
