# Generated by Django 2.2.2 on 2019-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='languages',
            field=models.CharField(default='c', max_length=9),
        ),
    ]
