# Generated by Django 2.2.2 on 2019-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20191023_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='languages',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c', 'c'), ('c++', 'c++')], default='c', max_length=9),
        ),
    ]
