# Generated by Django 2.2.2 on 2019-10-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20191023_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('queue', 'queue'), ('OK', 'OK'), ('CTE', 'CTE'), ('RTE', 'RTE')], default='queue', max_length=5),
        ),
    ]
