# Generated by Django 2.2.2 on 2019-10-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20191023_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='box',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
