# Generated by Django 2.2.2 on 2019-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_submission_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='box',
            field=models.SmallIntegerField(null=True),
        ),
    ]
