# Generated by Django 2.2.2 on 2019-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20191111_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='exctime',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mem',
            field=models.IntegerField(null=True),
        ),
    ]
