# Generated by Django 2.2.2 on 2019-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20191111_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='exctime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mem',
            field=models.TextField(null=True),
        ),
    ]
